### ISSUE TITLE
Improve report obs/fx pair creation

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter_dashboard#112]
Currently, selecting this an observation limits the forecast selection to forecasts at the same site. 
Possible enhancements:
- Work Both ways: Selecting a Forecast limits the Observation options
- Limit options by variable. Currently users can select different variables for the same pair which will cause the report to fail.

**Comment by lboeman** [comment]
Creating a selector that allows users to narrow by Sites -> Forecasts -> Observations for the next stakeholder webinar.

**Comment by lboeman** [comment]
Update the form to retain obs/fx pairs when an error occurs at the API.

**Comment by wholmgren** [comment]
> Update the form to retain obs/fx pairs when an error occurs at the API.

Seems like a separate issue. At minimum rename this one.
