### ISSUE TITLE
Data sharing interface

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter_dashboard#117]
The initial design of the data sharing interface should parallel the manual controls exposed by the API. Simpler call-to-action type interface should be implemented later.

**Comment by lboeman** [comment]
Running into need for a user information type of endpoint for the API, to filter RBAC objects by the current admin's organization such that they don't run into errors trying to add other organization's objects to their RBAC objects.

**Comment by wholmgren** [comment]
what's the status of this? Seems like it might be complete.

**Comment by lboeman** [comment]
I think this can be closed and specific issues can be opened moving forward. I think the basic functionality is complete here.
