### ISSUE TITLE
logged in as doesn't always show up

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#129]
Clicking the "Account" menu presumably should show the same info no matter where you are, but the logged in as info doesn't show up on at least one page (admin/users/uuid).

<img width="1368" alt="Screen Shot 2019-10-03 at 3 36 43 PM" src="https://user-images.githubusercontent.com/4383303/66168987-b64faf80-e5f3-11e9-93c4-d59d862f7868.png">

**Comment by lboeman** [comment]
I fixed this today. Should be fixed on prod. I was injecting a 'user' variable to provide that data, and on the user pages also using 'user' as a template variable for metadata of the user you're viewing.
#128 closes this.
