### ISSUE TITLE
aggregate 422

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#161]
two questions:

1. why is there a 422?
2. can we display more helpful information to the user?

<img width="1552" alt="Screen Shot 2019-11-18 at 11 58 52 AM" src="https://user-images.githubusercontent.com/4383303/69081357-05627000-09fb-11ea-92d0-ad46b3ca482c.png">

**Comment by alorenzo175** [comment]
1. There is no data for the SURFRAD sites for that period (-3 days to now)
2. Yes, we should use the messages raised in https://github.com/SolarArbiter/solarforecastarbiter-core/blob/6bac22376589aa47834cdac68705f83d2395bdcf/solarforecastarbiter/utils.py#L71 to set the 422 text
