### ISSUE TITLE
Report styling updates

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter_dashboard#201]
Some notes on report styles after reviewing a dashboard report pre-beta4 webinar:

- [x] Vertical divider between aligned pairs, observations and forecasts in the *Table of data alignment parameters* table might help make the table more readable.

- [ ] It would be nice if the timeseries plots only covered the existing data range.
- [x] Metric section headers (the buttons for collapsing/expanding) could be smaller. Probably move class to h4, and reduce padding.
- [ ] Try to wrangle the bokeh plots into their containing divs.

**Comment by lboeman** [comment]
For the remaining two issues of setting the initial zoom range of the plots to only include existing data, and to wrangle the divs into their respective container's we're probably going to want to use BokehJS. 
Displaying available data is going to be easier by adding the `name` parameter to the ColumnDataSource objects created in https://github.com/SolarArbiter/solarforecastarbiter-core/blob/6d9f7a0dd47f0f2cb4dbb7f3521ad5ab690f6f75/solarforecastarbiter/reports/figures.py#L42. This will allow the data to be accessible from BokehJS.

We might need to include the `bokeh-api` library to the dashboard (found: https://docs.bokeh.org/en/latest/docs/installation.html#install-bokehjs ) to update these features dynamically. But BokehJS doesn't have very good documentation, and I wasn't able to get these done quickly so I'm leaving for now.
The general code for setting the x range of the timeseries plots should be something along the lines of: 
`
var timeseries_data = Bokeh.documents[0].get_model_by_name('value_cds').data; // assuming the name attribute has been added as mentioned above
var start = Math.min(...timeseries_data);
var end = Math.max(...timeseries_data);
Bokeh.documents[0].get_model_by_name('timeseries').x_range.setv({start: min, end: max})
`
However, this does not work as expected.

**Comment by alorenzo175** [comment]
Seems like the plotly transition has solved the issues here?

**Comment by lboeman** [comment]
Yes. Will pointed out a small issue with "total" plot labels running out of the div, which I'm trying to fix quickly.

**Comment by alorenzo175** [comment]
After https://github.com/SolarArbiter/solarforecastarbiter-core/pull/388, seems like the things listed here are taken care of

**Comment by lboeman** [comment]
Yes, agreed.
