### ISSUE TITLE
Improve report loading and performance for large reports

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter_dashboard#206]
Reports load slowly when lots of bokeh plots are included. My initial idea of removing the empty bk-root divs from the document before bokeh can render them caused Bokeh to throw an error and complain with `Uncaught Error: Error rendering Bokeh model: could not find #387798b3-e20e-46e0-9038-193b78a2aecd HTML tag`, so that's not a viable solution. 

We might have to move to a lighter-weight plotting library for performance, at lease for the metrics plots.

**Comment by alorenzo175** [comment]
I wonder if we could split up making the script/divs a little more https://github.com/SolarArbiter/solarforecastarbiter-core/blob/6d9f7a0dd47f0f2cb4dbb7f3521ad5ab690f6f75/solarforecastarbiter/reports/figures.py#L702.  One issue might be making sure there is only one copy of the metrics CDS

**Comment by lboeman** [comment]
That's a good idea, I'll see if that helps. I am concerned about having to handle calling bokeh instead of just letting document.ready kick off the drawing but perhaps it's something simple to do with BokehJS.

**Comment by lboeman** [comment]
This was mostly handled in https://github.com/SolarArbiter/solarforecastarbiter-core/pull/359.

We found that BokehJS wasn't really mature enough to quickly and effectively accomplish this, so we coverted report plots to Plotly.
