### ISSUE TITLE
add reference forecast option to report form

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#214]
The user interface and/or API is the most challenging part of this. I'm sure core can adapt to whatever we need.

I think the core calculator code assumes a single reference forecast for all objects, so we should take that approach here too. 

We'll need to restrict reports to a single variable in order for this to make sense. 

Maybe `'reference_forecast'` is a new kind of key in `report_objects`?

@lboeman how much effort do you think this is going to be?

**Comment by lboeman** [comment]
I think I need to understand how the reference forecasts are being utilized in the report. 

If we're assuming a single reference forecast, does that imply that the site, variable and possible forecasts and observations are already limited by the choice of reference forecast?

Is a reference forecast always required?

Are there any restrictions on which forecasts can be a "reference forecast"?   

It seems like the UI should be altered to make the following selections:

1.  a variable selection to make a blanket filter
2. A reference forecast (or Site if reference forecast field is optional), so we can infer location data and limit the forecast/observation pairs.
3. fx/obs pair selection.

If those thoughts are in the ballpark, I think this should be ~ 3 days of work.

**Comment by wholmgren** [comment]
> If we're assuming a single reference forecast, does that imply that the site, variable and possible forecasts and observations are already limited by the choice of reference forecast?

It implies that they are limited. The reference forecast needs to be for the same observation as a regular forecast. I'm not sure about "already" since it could go in either direction.

> Is a reference forecast always required?

No

> Are there any restrictions on which forecasts can be a "reference forecast"?

Not that I can think of.

Looking again at the core `calculator` and `preprocessing` code, I'm a little concerned that we might need to change things so that the reference forecast is validated along with the forecast and observations. This would make it easier to supply a unique reference forecast for each forecast/observation pair in core, which could be used or not in the dashboard/api.

I can imagine that people might want to do something like "compare forecast skill metrics for each test forecast at each SURFRAD site". You end up with a graph that shows forecast skill like any other metric. Perhaps the labels are twice as long for clarity about what's being shown.

In any case, the interface could look something like below

<img width="671" alt="Screen Shot 2020-03-30 at 3 01 20 PM" src="https://user-images.githubusercontent.com/4383303/77966201-66e2f700-7297-11ea-9884-664f9ab5f57e.png">

**Comment by lboeman** [comment]
That's a lot more straightforward than what I was thinking. It should be pretty quick to implement.

**Comment by wholmgren** [comment]
@alorenzo175 your thoughts on the above?

**Comment by alorenzo175** [comment]
I agree that we a reference forecast per fx/obs pair. I think it would be nice to have the reference forecasts pre-selected on later fx/obs pairs based on the the first one (i.e. {site} Intraday HRR ghi)

**Comment by wholmgren** [comment]
Thanks. Thinking out loud... maybe we'll need a callback or something that enforces a forecast skill metric when reference forecasts are selected and prevents it when they are not.

**Comment by lboeman** [comment]
I think that's something that makes it a little more tricky. Do we want to enforce reference forecasts for every pair when certain metrics are selected, or just log a message when computing the metric isn't possible?

**Comment by wholmgren** [comment]
Assuming reference forecasts are assigned for each fx/obs pair then we probably do *not* want to require them for all pairs or no pairs. Could we verify the combinations when clicking "submit" and stay on the page if they're not valid? The check would be something like 

```
ref_fx = [none, 123-456, none, none, 348-786]
ref_fx_exists = some(ref_fx)
if (ref_fx_exists && !metrics.Skill.checked) { insert_warning_div_and_dont_post() }
else if (!ref_fx_exists && metrics.Skill.checked) { insert_different_div_and_dont_post() }
```

I don't know anything about how the javascript works on that page, but hopefully that's translatable.

**Comment by wholmgren** [comment]
I had forgotten that the data model already supports one reference forecast per fx/obs pair:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/datamodel.py#L922

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/datamodel.py#L951

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/datamodel.py#L1156

**Comment by lboeman** [comment]
Is the reference forecast subject to the same restrictions are the forecast-observation relationship? e.g. reference forecast must have an interval_length <= that of the forecast?

**Comment by wholmgren** [comment]
Yes
