### ISSUE TITLE
enforce unit consistency in reports

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter_dashboard#217]
The core datamodel checks for unit consistency for forecast/observations in a report. Maybe we should go further and ensure the variable is the same instead of just the units, but either way the report form should validate for these inconsistencies so we don't get a failed report

**Comment by lboeman** [comment]
Ah, so I was trying to figure out what went wrong here. Do the variable and units need to match across all of the pairs in a report?

**Comment by alorenzo175** [comment]
Currently, units need to match across all pairs in the report.  We could take that a step further and ensure all variables match, although if we decide to do that, we should update the datamodel too.

**Comment by wholmgren** [comment]
I’d like to relax the restriction in the future. Seems doable to group the analysis and templating by variable or unit.
