### ISSUE TITLE
option to account for uncertainty in report

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#218]
https://github.com/SolarArbiter/solarforecastarbiter-core/pull/378 adds a capability for core to account for uncertainty in reports. This needs to be exposed on the dashboard too.

One suggestion is radio buttons for:

* Ignore uncertainty --> {'deadband': null}
* Set deadband to observation uncertainties --> {'deadband': 'observation_uncertainty'}
* Set deadband for all observations: --> {'deadband': input box value}

These would live near the metrics check boxes. 

Another option is to put the selection boxes within the "Observation, Forecast pairs" section and allow the user to set the deadband for each pair. That seems a little ambitious for now, though.

What do you think of feasibility @lboeman?

**Comment by lboeman** [comment]
Sounds pretty doable. Are we just adding `deadband` to the report parameters, or do we need a  field for the source of the deadband, and one for the value?

**Comment by wholmgren** [comment]
On the call we agreed that it was reasonable to implement this on each forecast/observation pair. Radio buttons would go right before the "Add a Forecast, Observation pair" button. Buttons are to be:

* Ignore uncertainty [JSON value of null?]
* Set deadband to observation uncertainty: (print value from metadata with units) [JSON value of 'observation_uncertainty' or similar]
* Set deadband to: (input text box + units string) [JSON value of text box value]

Sound right @lboeman?

**Comment by lboeman** [comment]
Yes that sounds right to me. Just to clarify, when a user selects "set deadband to observation uncertainty" we display and add the value to the report's json, but don't allow the user to update it?

**Comment by wholmgren** [comment]
I was thinking it would be a string in that case. I thought that was @atlorenzo175 preference but could have misunderstood.

**Comment by alorenzo175** [comment]
Yes, that was my preference so that it would be easy to replicate if the report parameters json are constructed manually and posted to the api

**Comment by lboeman** [comment]
ahh, I get it. Sorry I was unclear and made this way more confusing than it needs to be. So the `deadband` field should be a string (in place of the "uncertainty" field I have above) with three options. `null`, `observation_uncertainty` or a float representing uncertainty as a percentage (encoded as a string).
