### ISSUE TITLE
"Set deadband to observation uncertainty" needs a number

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#227]
Users should be able to determine what the deadband is for "Set deadband to observation uncertainty." before computing the report. Ideally, it would show up in both the report form and the observation metadata.

<img width="853" alt="Screen Shot 2020-04-23 at 11 23 16 AM" src="https://user-images.githubusercontent.com/4383303/80135334-f1e0a580-8554-11ea-9799-0bcc27736db8.png">
<img width="865" alt="Screen Shot 2020-04-23 at 11 23 27 AM" src="https://user-images.githubusercontent.com/4383303/80135335-f311d280-8554-11ea-93e5-7da811fc0fe7.png">

**Comment by wholmgren** [comment]
also the "Set deadband to" field is way bigger than it needs to be.

**Comment by lboeman** [comment]
The observation uncertainty when the pair gets added to the report. Should it just populate at the end of the option? e.g. 
Set deadband to observation uncertainty: 5.0%

**Comment by wholmgren** [comment]
Add % when a number is specified:

<img width="813" alt="Screen Shot 2020-04-23 at 11 28 36 AM" src="https://user-images.githubusercontent.com/4383303/80135814-a5499a00-8555-11ea-8ba7-f002bfc70353.png">

No period here:

<img width="815" alt="Screen Shot 2020-04-23 at 11 28 28 AM" src="https://user-images.githubusercontent.com/4383303/80135816-a5e23080-8555-11ea-832c-c3a0fdfaf0d5.png">

nor in the selection options

> Should it also populate at the end of the option?

Yes, click on an observation and the value updates.

**Comment by wholmgren** [comment]
<img width="809" alt="Screen Shot 2020-04-23 at 4 06 54 PM" src="https://user-images.githubusercontent.com/4383303/80158120-91655e80-857c-11ea-822a-d6238f3c88c1.png">

Still no % after a user specified value
