### ISSUE TITLE
deleting a report shows incomplete table

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#232]
the metrics are not shown, perhaps because they're for an event forecast

<img width="852" alt="Screen Shot 2020-04-23 at 4 27 43 PM" src="https://user-images.githubusercontent.com/4383303/80159279-6cbeb600-857f-11ea-82d7-ea8f8f3a7b42.png">

@lboeman ?

**Comment by wholmgren** [comment]
I guess I would have expected that it would list the forecast/obs pairs too. but that's probably another issue.

**Comment by lboeman** [comment]
The object pairs only exist in the API response as an object with uuids, so I haven't loaded the metadata to display them before. It could definitely be done if that's useful.
