### ISSUE TITLE
all quantities shown as minutes instead of hours or days

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#37]
run length = 1440 minutes is not very friendly. Would be nicer to display on the dashboard as 1 day. Same issue could applies to forecasts that have lengths that are integer multiples of 60 minutes. I only noticed it on the run length field, but maybe also applies to other fields.

**Comment by lboeman** [comment]
All of the time interval fields have this same display. Are you thinking of a format like `# days #hours #minutes` where we'd drop a field if it was 0 (i.e. 1500 minutes would be `1 day 1 hour`)?

**Comment by wholmgren** [comment]
Yes, something like that.
