### ISSUE TITLE
more bokeh controls

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter_dashboard#59]
I expect most plots should have box zoom and save. Crosshairs? Hover? Zoom in and zoom out icons might be easier to immediately identify, maybe add them too. 

Things like selection and lasso are probably best addressed in beta.

**Comment by wholmgren** [comment]
@alorenzo175 sounds like you're on your way to closing this with your validation graphics.

**Comment by alorenzo175** [comment]
yes #76

**Comment by lboeman** [comment]
closed by #76
