### ISSUE TITLE
add comment form

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter_dashboard#78]
It doesn't look like Sentry will quite work for what we want, so lets go with a google form

**Comment by wholmgren** [comment]
feel free to edit this https://docs.google.com/forms/d/e/1FAIpQLSesG5GUMzcvDOVipyzdhaNIukBDNMfoQFrNB3vnGsUUP6NzcA/viewform?usp=sf_link
